Add custom http client option to GraphQLClient
movio/bramble pull request #122
Opened 2022-02-15 07:30 UTC by jainpiyush19

2022-02-15 07:30 UTC, jainpiyush19 commented
https://github.com/movio/bramble/issues/121

2022-02-17 00:40 UTC, lucianjon requested changes
Thanks @jainpiyush19! Just a couple of comments around the test but otherwise LGTM.

2022-02-17 03:24 UTC, pkqk commented on config.go
> +	if c.QueryHTTPClient != nil {
Making a custom `main.go` would probably also be enough for now but a custom plugin is the most flexible option.

2022-02-17 03:36 UTC, pkqk approved these changes

2022-02-17 21:27 UTC, pkqk commented
Thanks @jainpiyush19, we'll merge this in as it is, but an example plugin that shows the custom HTTPClient being used would also be appreciated.

2022-02-17 21:30 UTC, merged